// AUTO-GENERATED by the bot repo's scripts/gen-faq-defaults.mjs — DO NOT EDIT.
// Source of truth: the bot's src/faq/entries.ts + src/router/menu.ts.
// Regenerate after editing FAQ banks: (in the bot repo) npm run build &&
// node scripts/gen-faq-defaults.mjs
//
// The FAQ editor renders these defaults; only edited entries are persisted to
// faq_overrides (the diff). The bot overlays that diff fail-open.

export interface FaqDefaultEntry {
  id: string
  shortLabel: string
  question: string
  /** Each element is one WhatsApp message bubble. */
  answer: string[]
}

export interface FaqDefaultGroup {
  slug: string
  displayName: string
  isGlobal: boolean
  entries: FaqDefaultEntry[]
}

export const FAQ_DEFAULTS: FaqDefaultGroup[] = [
  {
    "slug": "tatuajes",
    "displayName": "Eliminación de tatuajes",
    "isGlobal": false,
    "entries": [
      {
        "id": "tat:duele",
        "shortLabel": "¿Duele?",
        "question": "¿Duele la eliminación de tatuajes con láser?",
        "answer": [
          "La mayoría de los pacientes tolera muy bien el tratamiento 😊\nAproximadamente un 85% realiza las sesiones sin necesidad de anestesia.",
          "En algunos casos utilizamos anestesia en crema para mayor confort (alrededor del 10% de los pacientes).",
          "Y en un pequeño porcentaje, nuestro médico puede infiltrar la zona con pequeños pinchazos y aplicar anestesia local antes de comenzar.",
          "La sensación suele describirse como pequeños pinchazos o el chasquido de una bandita elástica sobre la piel. Además, cada disparo dura milésimas de segundo, por lo que las sesiones suelen ser rápidas."
        ]
      },
      {
        "id": "tat:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones necesito?",
        "answer": [
          "Es imposible determinar a simple vista cuánto se va a eliminar de un tatuaje en una primera sesión o cuántas sesiones serán necesarias para eliminarlo completamente.",
          "Esto depende de muchos factores:\n👉 la calidad, cantidad, color y profundidad de la tinta utilizada.\n👉 la zona del cuerpo\n👉 si existe fibrosis o cicatrices internas\n👉 y el propio organismo del paciente, que es quien elimina las partículas fragmentadas por el láser.",
          "Muchos de estos factores no pueden evaluarse simplemente observando el tatuaje, por eso no es serio prometer resultados exactos ni \"eliminación en una sesión\".",
          "La cantidad de sesiones la determina el Dr. según la evolución posterior a la primera sesión y la respuesta real del tatuaje al láser PicoSure."
        ]
      },
      {
        "id": "tat:cadencia",
        "shortLabel": "¿Cada cuánto?",
        "question": "¿Cada cuánto tiempo se hacen las sesiones?",
        "answer": [
          "Las sesiones suelen realizarse cada 4, 6 u 8 semanas aproximadamente, dependiendo de la cantidad de tinta, la calidad de los pigmentos utilizados y la reacción del tatuaje a las sesiones de láser.",
          "Cada tatuaje responde de manera diferente, por eso los tiempos pueden variar según la evolución del tratamiento."
        ]
      },
      {
        "id": "tat:colores",
        "shortLabel": "¿Qué color cuesta más?",
        "question": "¿Qué color es más difícil de eliminar?",
        "answer": [
          "Los colores negros y grises oscuros son los que mejor responden al láser.",
          "Los colores más difíciles de eliminar son: *verde, celeste, azul y turquesa*. Estos pigmentos son altamente resistentes a la mayoría de los equipos láser convencionales.",
          "PicoSure trabaja mediante un efecto fotoacústico que fragmenta la tinta en partículas muy pequeñas, facilitando su eliminación progresiva por el organismo.",
          "👉 En Argentina existen muy pocos equipos PicoSure originales — esto hace una diferencia enorme en el resultado final del tratamiento."
        ]
      },
      {
        "id": "tat:cuidados",
        "shortLabel": "Cuidados entre sesiones",
        "question": "¿Qué cuidados debo tener entre sesiones?",
        "answer": [
          "Mantener la zona limpia, evitar sol directo y no rascar ni exfoliar. Nuestro médico antes, durante y después del tratamiento te va a explicar cómo realizar los cuidados necesarios para tener los mejores resultados."
        ]
      },
      {
        "id": "tat:cicatrices",
        "shortLabel": "¿Quedan cicatrices?",
        "question": "¿Quedan cicatrices?",
        "answer": [
          "Cuando el tratamiento se realiza con tecnología adecuada y bajo supervisión médica, el riesgo de cicatrices es muy bajo.",
          "PicoSure trabaja con pulsos ultracortos de picosegundos que fragmentan la tinta por un efecto mecánico - acústico cuidando la piel comparado con tecnologías más antiguas.",
          "⚠️ Sin embargo, existen factores que pueden aumentar el riesgo:\n- mala cicatrización previa,\n- tatuajes con fibrosis o relieve,\n- manipulación incorrecta de costras,\n- exposición solar,\n- o tratamientos agresivos realizados anteriormente.",
          "👉 Por eso cada caso debe evaluarse individualmente y el tratamiento debe realizarse con parámetros médicos adecuados."
        ]
      },
      {
        "id": "tat:volver_tatuar",
        "shortLabel": "¿Volver a tatuar?",
        "question": "¿Se puede volver a tatuar encima?",
        "answer": [
          "Sí, en la mayoría de los casos se puede realizar un cover o volver a tatuar la zona una vez finalizado el tratamiento y recuperada correctamente la piel.",
          "De hecho, muchas personas realizan algunas sesiones de eliminación para aclarar el tatuaje y luego hacerse un nuevo diseño encima.",
          "✨ Una buena eliminación previa permite lograr covers más limpios, con mejores colores y menos saturación de tinta.",
          "⚠️ El tiempo para volver a tatuar depende de:\n- la recuperación de la piel,\n- la cantidad de sesiones realizadas,\n- y la evolución individual de cada paciente.\n\n👉 La evaluación final la realiza el Dr según la respuesta de la piel al tratamiento."
        ]
      },
      {
        "id": "tat:microblading",
        "shortLabel": "¿Microblading?",
        "question": "¿También tratan microblading o pigmentación de cejas?",
        "answer": [
          "Sí 👍\n\nLa eliminación de microblading se realiza con el mismo tratamiento que los tatuajes — es pigmento implantado en la piel y responde a las mismas tecnologías láser.",
          "✨ Trabajamos con tecnología *PicoSure original*, que permite eliminar pigmentos de microblading de forma progresiva y segura, cuidando la zona delicada de la ceja.",
          "👉 La cotización se realiza igual que el resto de los tatuajes, midiendo el área pigmentada y evaluando color y profundidad."
        ]
      },
      {
        "id": "tat:picosure_vs",
        "shortLabel": "PicoSure vs otros",
        "question": "¿Qué diferencia hay entre PicoSure y otros láseres?",
        "answer": [
          "No todos los equipos para eliminación de tatuajes funcionan igual.",
          "Muchos centros utilizan tecnologías antiguas o equipos genéricos que trabajan principalmente por calor y pueden requerir más sesiones o generar mayor agresión sobre la piel.",
          "En Corpo Bello Medicina Láser trabajamos con PicoSure original, tecnología láser Alexandrita de picosegundos, considerada una de las más avanzadas del mundo para eliminación de tatuajes.",
          "✨ PicoSure fragmenta la tinta en partículas extremadamente pequeñas utilizando un efecto fotoacústico.\n\nEsto permite:\n- mejor respuesta en colores difíciles,\n- sesiones más eficientes,\n- menor daño térmico,\n- y mejor recuperación de la piel.",
          "👉 Además, es uno de los pocos equipos con excelente respuesta en colores como verde, celeste, azul y turquesa.\n\n⚠️ En Argentina existen muy pocos equipos PicoSure originales."
        ]
      },
      {
        "id": "tat:ubicacion",
        "shortLabel": "Ubicación y horarios",
        "question": "¿Dónde y en qué horarios se realiza este tratamiento?",
        "answer": [
          "Este tratamiento se realiza en nuestros consultorios médicos de:\n\n📍 Caballito (CABA)\n- Dos jueves al mes de 14 a 20 hs\n- y un sábado al mes de 14 a 20 hs\n\n📍 Merlo\n- Martes de 9 a 20 hs",
          "⚠️ En Moreno actualmente solo realizamos depilación láser Soprano Ice.\n\n👉 Los turnos son únicamente con reserva previa."
        ]
      }
    ]
  },
  {
    "slug": "depilacion-laser",
    "displayName": "Depilación Láser",
    "isGlobal": false,
    "entries": [
      {
        "id": "lsr:diferencial",
        "shortLabel": "¿Qué nos diferencia?",
        "question": "¿Qué diferencia a Corpo Bello de otros centros?",
        "answer": [
          "En Corpo Bello realizamos depilación láser en consultorios médicos habilitados, con equipos habilitados por ANMAT y bajo supervisión médica.",
          "❄️ Trabajamos con tecnología Soprano Ice original de Alma Lasers, utilizando equipos propios y calibrados. No alquilamos equipos.\n\nEsto nos permite adaptar los tiempos entre sesiones según:\n• la fase de crecimiento del vello\n• la evolución real del tratamiento\n• el tipo de piel y vello\n• y la respuesta individual de cada paciente.",
          "📆 Por eso no todos los pacientes se tratan igual ni siempre cada 30 días. Dependiendo de la evolución, las sesiones pueden realizarse cada 30, 45 o 60 días para lograr mejores resultados.",
          "👨‍⚕️ Los tratamientos son realizados por personal de salud y supervisados médicamente, ajustando parámetros de forma personalizada en cada sesión.",
          "⏱️ También respetamos los tiempos reales de tratamiento. Muchos centros realizan múltiples zonas en pocos minutos para atender más pacientes por día.",
          "📍 Una pierna completa puede llevarnos el tiempo que otros lugares utilizan para realizar varias zonas juntas, porque priorizamos trabajar de forma correcta, uniforme y segura, sin acelerar el procedimiento innecesariamente."
        ]
      },
      {
        "id": "lsr:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones necesito para depilación definitiva?",
        "answer": [
          "En promedio entre 8 y 10 sesiones, dependiendo de la zona y el tipo de piel."
        ]
      },
      {
        "id": "lsr:duele",
        "shortLabel": "¿Duele?",
        "question": "¿La depilación láser duele?",
        "answer": [
          "La depilación láser con tecnología Soprano Ice original suele ser muy bien tolerada. 🙌",
          "La mayoría de los pacientes siente únicamente una sensación de calor en la zona durante el procedimiento.",
          "En pacientes más sensibles, podemos indicar anestesia en crema previamente para mayor confort.",
          "❄️ El sistema de enfriamiento continuo del equipo ayuda a que el tratamiento sea mucho más cómodo comparado con tecnologías más antiguas."
        ]
      },
      {
        "id": "lsr:cadencia",
        "shortLabel": "¿Cada cuánto?",
        "question": "¿Cada cuánto tiempo debo hacerme las sesiones?",
        "answer": [
          "Esto es importante: en muchos lugares hacen una sesión por mes sin conocimiento previo. En nuestro centro médico oficial Soprano Ice se hacen cada 30 - 45 - 60 días, según la zona, etapa de crecimiento del vello y fototipo de piel."
        ]
      },
      {
        "id": "lsr:piel",
        "shortLabel": "Tipos de piel",
        "question": "¿Es apto para todo tipo de piel?",
        "answer": [
          "Sí, el equipo está diseñado para todo fototipo de piel, incluso pieles bronceadas."
        ]
      },
      {
        "id": "lsr:cuidados",
        "shortLabel": "Cuidados después",
        "question": "¿Qué cuidados debo tener después del láser?",
        "answer": [
          "Evitar sol, sauna y piscina por unos días. Usar protector solar y mantener la piel hidratada."
        ]
      },
      {
        "id": "lsr:sedes",
        "shortLabel": "¿Dónde están?",
        "question": "¿Dónde están ubicados?",
        "answer": [
          "📍 Contamos con consultorios médicos en:\n• Merlo\n• Caballito\n• Moreno"
        ]
      }
    ]
  },
  {
    "slug": "acne-activo",
    "displayName": "Acné activo",
    "isGlobal": false,
    "entries": [
      {
        "id": "acne:granos",
        "shortLabel": "¿Granos inflamados?",
        "question": "¿Sirve si tengo granos inflamados?",
        "answer": [
          "Sí 👍\n\nEl tratamiento puede utilizarse incluso en pacientes con acné inflamatorio activo.",
          "Dependiendo del tipo de lesión y sensibilidad de la piel, el protocolo se adapta para ayudar a disminuir inflamación, enrojecimiento y brotes activos de forma progresiva."
        ]
      },
      {
        "id": "acne:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones suelen hacerse?",
        "answer": [
          "La cantidad de sesiones varía (entre 6 a 8) según:\n• el tipo de acné\n• la inflamación\n• la evolución\n• y la respuesta individual de la piel.",
          "Algunos pacientes observan mejoras desde las primeras sesiones, aunque generalmente se realizan protocolos progresivos y personalizados."
        ]
      },
      {
        "id": "acne:marcas",
        "shortLabel": "¿Marcas o manchas?",
        "question": "¿Puede ayudar con marcas o manchas de acné?",
        "answer": [
          "Sí 🙌\n\nAdemás de ayudar con el acné activo, muchos pacientes observan mejora en:\n• manchas residuales\n• marcas rojas\n• textura irregular\n• y aspecto general de la piel.",
          "En algunos casos puede combinarse posteriormente con tratamientos específicos para secuelas de acné."
        ]
      },
      {
        "id": "acne:adolescentes",
        "shortLabel": "¿En adolescentes?",
        "question": "¿Se puede realizar en adolescentes?",
        "answer": [
          "Sí 👍\n\nEl tratamiento puede realizarse en adolescentes, adaptando siempre el protocolo según la edad, el tipo de acné y la sensibilidad de la piel.",
          "👨‍⚕️ Al trabajar bajo supervisión médica, evaluamos cada caso de forma personalizada para indicar el tratamiento más adecuado."
        ]
      },
      {
        "id": "acne:medicacion",
        "shortLabel": "¿Si uso medicación?",
        "question": "¿Puedo hacerme el tratamiento si uso medicación para el acné?",
        "answer": [
          "Depende del tipo de medicación y del estado actual de la piel.\n\nPor eso es importante enviar una foto y comentar si estás utilizando tratamientos médicos o dermatológicos para poder orientarte correctamente."
        ]
      },
      {
        "id": "acne:irrita",
        "shortLabel": "¿Irrita la piel?",
        "question": "¿La piel puede irritarse o brotarse después?",
        "answer": [
          "Después del tratamiento puede aparecer un leve enrojecimiento o sensibilidad transitoria, que normalmente mejora en poco tiempo.",
          "En algunos pacientes el proceso inflamatorio del acné puede ir cambiando progresivamente durante las sesiones, por eso los tratamientos se ajustan según la evolución de cada piel."
        ]
      },
      {
        "id": "acne:isotretinoina",
        "shortLabel": "¿Si tomo Isotretinoína?",
        "question": "¿Si tomo Isotretinoína / medicamentos me lo puedo hacer?",
        "answer": [
          "¡Sí, perfectamente! 🩺\n\nGracias a que en Corpo Bello contamos con tecnología láser médica premium de última generación (como *Picosure*), el estímulo sobre la piel es fotomecánico y ultra veloz, no térmico.\n\nEsto significa que, a diferencia de los láseres antiguos o agresivos como el láser CO2, es 100% seguro realizarlo si estás tomando *Isotretinoína (Roacután)* u otros medicamentos: el Dr. calibra los parámetros exactos y seguros para tu condición actual.\n\n⚠️ Lo único que te pedimos es que si estás usando ácidos fuertes en crema o antibióticos, los consignes en la historia clínica al realizar la sesión, para darte las indicaciones previas."
        ]
      },
      {
        "id": "acne:vuelta_actividades",
        "shortLabel": "¿Vuelvo a mi rutina?",
        "question": "¿Puedo volver a mis actividades ya mismo?",
        "answer": [
          "¡Sí, absolutamente de inmediato! Al ser una tecnología médica ultra precisa y avanzada, la piel no se quema, no se ampolla ni genera costras agresivas como el Láser CO2.",
          "Al salir del consultorio podés volver a trabajar, estudiar o hacer tu rutina normal. Lo único que podés llegar a notar es un enrojecimiento muy sutil y temporario que desaparece a los pocos minutos, el cual podés cubrir con protector solar con color o maquillaje sin ningún inconveniente."
        ]
      }
    ]
  },
  {
    "slug": "secuelas-acne",
    "displayName": "Secuelas de acné",
    "isGlobal": false,
    "entries": [
      {
        "id": "sec:pozos",
        "shortLabel": "¿Pozos profundos?",
        "question": "¿Sirve para pozos y cicatrices profundas?",
        "answer": [
          "Sí 👍\n\nDependiendo del tipo y profundidad de las secuelas, pueden utilizarse distintos protocolos para mejorar:\n• textura\n• irregularidades\n• fibrosis\n• y cicatrices deprimidas.",
          "En algunos pacientes se indican tratamientos láser y en otros puede recomendarse *Endolift* o protocolos combinados para trabajar planos más profundos de la piel."
        ]
      },
      {
        "id": "sec:desaparecen",
        "shortLabel": "¿Desaparecen del todo?",
        "question": "¿Las cicatrices desaparecen completamente?",
        "answer": [
          "Las secuelas de acné pueden mejorar muchísimo, aunque el grado de mejoría depende de:\n• profundidad\n• fibrosis\n• antigüedad\n• y respuesta individual de la piel.\n\nPor eso los tratamientos son personalizados y progresivos según cada paciente."
        ]
      },
      {
        "id": "sec:laser_vs_endolift",
        "shortLabel": "¿Láser vs Endolift?",
        "question": "¿Qué diferencia hay entre láser y Endolift?",
        "answer": [
          "El láser trabaja principalmente mejorando:\n• textura\n• manchas\n• calidad superficial\n• y estimulación de colágeno.",
          "*Endolift* permite además trabajar planos más profundos, fibrosis y retracciones mediante tecnología láser subdérmica mínimamente invasiva.",
          "👨‍⚕️ En algunos pacientes se indica uno de los tratamientos y en otros se combinan para lograr mejores resultados."
        ]
      },
      {
        "id": "sec:cambios",
        "shortLabel": "¿Cuándo se notan?",
        "question": "¿Cuándo se empiezan a notar los cambios?",
        "answer": [
          "Muchos pacientes observan mejoras progresivas en textura y calidad de piel desde las primeras sesiones.",
          "Sin embargo, la estimulación de colágeno y remodelación de la piel continúa evolucionando gradualmente con el tiempo."
        ]
      },
      {
        "id": "sec:combinable",
        "shortLabel": "¿Combinable?",
        "question": "¿Se puede combinar con otros tratamientos?",
        "answer": [
          "Sí 🙌\n\nDependiendo de cada caso, los protocolos pueden complementarse con:\n• láser\n• *Endolift*\n• y otros tratamientos médicos orientados a mejorar las secuelas de acné."
        ]
      },
      {
        "id": "sec:isotretinoina",
        "shortLabel": "¿Si tomo Isotretinoína?",
        "question": "¿Si tomo Isotretinoína / medicamentos me lo puedo hacer?",
        "answer": [
          "¡Sí, perfectamente! 🩺\n\nGracias a que en Corpo Bello contamos con tecnología láser médica premium de última generación (como *Picosure*), el estímulo sobre la piel es fotomecánico y ultra veloz, no térmico.\n\nEsto significa que, a diferencia de los láseres antiguos o agresivos como el láser CO2, es 100% seguro realizarlo si estás tomando *Isotretinoína (Roacután)* u otros medicamentos: el Dr. calibra los parámetros exactos y seguros para tu condición actual.\n\n⚠️ Lo único que te pedimos es que si estás usando ácidos fuertes en crema o antibióticos, los consignes en la historia clínica al realizar la sesión, para darte las indicaciones previas."
        ]
      },
      {
        "id": "sec:vuelta_actividades",
        "shortLabel": "¿Vuelvo a mi rutina?",
        "question": "¿Puedo volver a mis actividades ya mismo?",
        "answer": [
          "¡Sí, absolutamente de inmediato! Al ser una tecnología médica ultra precisa y avanzada, la piel no se quema, no se ampolla ni genera costras agresivas como el Láser CO2.",
          "Al salir del consultorio podés volver a trabajar, estudiar o hacer tu rutina normal. Lo único que podés llegar a notar es un enrojecimiento muy sutil y temporario que desaparece a los pocos minutos, el cual podés cubrir con protector solar con color o maquillaje sin ningún inconveniente."
        ]
      }
    ]
  },
  {
    "slug": "manchas-faciales",
    "displayName": "Manchas faciales",
    "isGlobal": false,
    "entries": [
      {
        "id": "mfac:tipos",
        "shortLabel": "¿Qué manchas trata?",
        "question": "¿Qué tipo de manchas pueden tratarse?",
        "answer": [
          "Dependiendo de cada caso, pueden trabajarse distintos tipos de pigmentaciones faciales asociadas a:\n• daño solar\n• envejecimiento\n• inflamación\n• secuelas\n• y otras alteraciones pigmentarias.",
          "👨‍⚕️ Por eso es importante evaluar previamente la piel antes de indicar un protocolo."
        ]
      },
      {
        "id": "mfac:desaparecen",
        "shortLabel": "¿Desaparecen del todo?",
        "question": "¿Las manchas desaparecen completamente?",
        "answer": [
          "La evolución depende de:\n• profundidad\n• tipo de pigmentación\n• tiempo de evolución\n• exposición solar\n• y respuesta individual de cada piel.\n\nMuchos pacientes observan mejoras progresivas en uniformidad y claridad de la piel utilizando tecnología PicoSure."
        ]
      },
      {
        "id": "mfac:picosure",
        "shortLabel": "¿Qué tiene PicoSure?",
        "question": "¿Qué diferencia tiene PicoSure?",
        "answer": [
          "PicoSure trabaja mediante un efecto fotoacústico que fragmenta la pigmentación en partículas muy pequeñas, ayudando a mejorar progresivamente el aspecto de la piel.",
          "👨‍⚕️ En Corpo Bello utilizamos protocolos personalizados ajustando parámetros según:\n• tipo de piel\n• sensibilidad\n• pigmentación\n• y evolución individual."
        ]
      },
      {
        "id": "mfac:verano",
        "shortLabel": "¿En verano?",
        "question": "¿Se puede hacer en verano?",
        "answer": [
          "Depende del grado de exposición solar y del estado actual de la piel.\n\nEn algunos casos pueden realizarse protocolos adaptados, siempre acompañados de cuidados adecuados y protección solar estricta."
        ]
      },
      {
        "id": "mfac:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones suelen hacerse?",
        "answer": [
          "La cantidad de sesiones varía según:\n• profundidad\n• tipo de mancha\n• tiempo de evolución\n• y respuesta individual de la piel.\n\nMuchos pacientes observan mejoras progresivas desde las primeras sesiones realizadas con tecnología PicoSure."
        ]
      },
      {
        "id": "mfac:isotretinoina",
        "shortLabel": "¿Si tomo Isotretinoína?",
        "question": "¿Si tomo Isotretinoína / medicamentos me lo puedo hacer?",
        "answer": [
          "¡Sí, perfectamente! 🩺\n\nGracias a que en Corpo Bello contamos con tecnología láser médica premium de última generación (como *Picosure*), el estímulo sobre la piel es fotomecánico y ultra veloz, no térmico.\n\nEsto significa que, a diferencia de los láseres antiguos o agresivos como el láser CO2, es 100% seguro realizarlo si estás tomando *Isotretinoína (Roacután)* u otros medicamentos: el Dr. calibra los parámetros exactos y seguros para tu condición actual.\n\n⚠️ Lo único que te pedimos es que si estás usando ácidos fuertes en crema o antibióticos, los consignes en la historia clínica al realizar la sesión, para darte las indicaciones previas."
        ]
      },
      {
        "id": "mfac:vuelta_actividades",
        "shortLabel": "¿Vuelvo a mi rutina?",
        "question": "¿Puedo volver a mis actividades ya mismo?",
        "answer": [
          "¡Sí, absolutamente de inmediato! Al ser una tecnología médica ultra precisa y avanzada, la piel no se quema, no se ampolla ni genera costras agresivas como el Láser CO2.",
          "Al salir del consultorio podés volver a trabajar, estudiar o hacer tu rutina normal. Lo único que podés llegar a notar es un enrojecimiento muy sutil y temporario que desaparece a los pocos minutos, el cual podés cubrir con protector solar con color o maquillaje sin ningún inconveniente."
        ]
      }
    ]
  },
  {
    "slug": "melasma",
    "displayName": "Melasma",
    "isGlobal": false,
    "entries": [
      {
        "id": "mel:volver",
        "shortLabel": "¿Puede volver?",
        "question": "¿El melasma puede volver?",
        "answer": [
          "Sí.\n\nEl melasma es una condición crónica y multifactorial, por lo que puede volver a activarse dependiendo de factores como:\n• exposición solar\n• calor\n• hormonas\n• estrés\n• inflamación\n• y cuidados posteriores.",
          "👨‍⚕️ Por eso en Corpo Bello utilizamos tecnología PicoSure dentro de protocolos personalizados orientados a mejorar y controlar progresivamente el melasma."
        ]
      },
      {
        "id": "mel:empeorar",
        "shortLabel": "¿Puede empeorarlo?",
        "question": "¿El tratamiento láser puede empeorar el melasma?",
        "answer": [
          "Si se utilizan protocolos inadecuados o demasiada agresión térmica, algunos tratamientos pueden empeorar la inflamación y la pigmentación.",
          "👨‍⚕️ Por eso en Corpo Bello trabajamos con tecnología PicoSure y protocolos personalizados, ajustando parámetros según:\n• tipo de piel\n• sensibilidad\n• profundidad\n• y evolución de cada paciente."
        ]
      },
      {
        "id": "mel:verano",
        "shortLabel": "¿En verano?",
        "question": "¿Se puede hacer en verano?",
        "answer": [
          "Depende del grado de exposición solar y del estado actual de la piel.\n\nEn muchos casos pueden realizarse protocolos adaptados utilizando tecnología PicoSure, siempre acompañados de cuidados adecuados y protección solar estricta."
        ]
      },
      {
        "id": "mel:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones suelen hacerse?",
        "answer": [
          "La cantidad de sesiones (entre 6 y 8) varía según:\n• profundidad\n• tiempo de evolución\n• tipo de melasma\n• y respuesta individual de cada paciente.\n\nMuchos pacientes observan mejoras progresivas con tecnología PicoSure, aunque los tratamientos suelen requerir seguimiento y mantenimiento."
        ]
      },
      {
        "id": "mel:mancha_comun",
        "shortLabel": "¿Igual a mancha común?",
        "question": "¿Es lo mismo que una mancha común?",
        "answer": [
          "No.\n\nEl melasma suele tener un componente más complejo y sensible que otras manchas pigmentarias comunes.",
          "👨‍⚕️ Por eso antes de trabajar con tecnología PicoSure es importante diferenciar correctamente:\n• tipo de pigmentación\n• profundidad\n• vascularización\n• y sensibilidad de la piel."
        ]
      },
      {
        "id": "mel:fallan",
        "shortLabel": "¿Por qué algunos fallan?",
        "question": "¿Por qué algunos tratamientos de melasma fallan o empeoran?",
        "answer": [
          "Porque no todos los melasmas son iguales y muchas veces se utilizan protocolos demasiado agresivos o estandarizados.",
          "👨‍⚕️ En Corpo Bello utilizamos tecnología PicoSure buscando trabajar de forma progresiva y personalizada, priorizando el control de la inflamación y la seguridad de la piel antes que tratamientos excesivamente agresivos."
        ]
      },
      {
        "id": "mel:isotretinoina",
        "shortLabel": "¿Si tomo Isotretinoína?",
        "question": "¿Si tomo Isotretinoína / medicamentos me lo puedo hacer?",
        "answer": [
          "¡Sí, perfectamente! 🩺\n\nGracias a que en Corpo Bello contamos con tecnología láser médica premium de última generación (como *Picosure*), el estímulo sobre la piel es fotomecánico y ultra veloz, no térmico.\n\nEsto significa que, a diferencia de los láseres antiguos o agresivos como el láser CO2, es 100% seguro realizarlo si estás tomando *Isotretinoína (Roacután)* u otros medicamentos: el Dr. calibra los parámetros exactos y seguros para tu condición actual.\n\n⚠️ Lo único que te pedimos es que si estás usando ácidos fuertes en crema o antibióticos, los consignes en la historia clínica al realizar la sesión, para darte las indicaciones previas."
        ]
      },
      {
        "id": "mel:vuelta_actividades",
        "shortLabel": "¿Vuelvo a mi rutina?",
        "question": "¿Puedo volver a mis actividades ya mismo?",
        "answer": [
          "¡Sí, absolutamente de inmediato! Al ser una tecnología médica ultra precisa y avanzada, la piel no se quema, no se ampolla ni genera costras agresivas como el Láser CO2.",
          "Al salir del consultorio podés volver a trabajar, estudiar o hacer tu rutina normal. Lo único que podés llegar a notar es un enrojecimiento muy sutil y temporario que desaparece a los pocos minutos, el cual podés cubrir con protector solar con color o maquillaje sin ningún inconveniente."
        ]
      }
    ]
  },
  {
    "slug": "pecas",
    "displayName": "Pecas",
    "isGlobal": false,
    "entries": [
      {
        "id": "pec:volver",
        "shortLabel": "¿Pueden volver?",
        "question": "¿Las pecas pueden volver?",
        "answer": [
          "Sí ☀️\n\nLas pecas suelen estar muy relacionadas con la exposición solar y la predisposición genética, por lo que pueden volver a pigmentarse con el tiempo si no se acompañan los tratamientos con cuidados adecuados y protección solar."
        ]
      },
      {
        "id": "pec:elimina_todas",
        "shortLabel": "¿Las elimina todas?",
        "question": "¿El tratamiento elimina todas las pecas?",
        "answer": [
          "Depende de:\n• profundidad\n• cantidad\n• pigmentación\n• y respuesta individual de cada piel.\n\nMuchos pacientes observan una mejora progresiva en uniformidad y luminosidad utilizando tecnología PicoSure."
        ]
      },
      {
        "id": "pec:artificial",
        "shortLabel": "¿Queda artificial?",
        "question": "¿La piel queda artificial o demasiado blanca?",
        "answer": [
          "No.\n\nNuestro objetivo no es \"borrar la identidad\" del rostro, sino ayudar a lograr una piel más uniforme, luminosa y saludable manteniendo un aspecto natural.",
          "👨‍⚕️ Por eso los protocolos se adaptan de forma personalizada según cada paciente."
        ]
      },
      {
        "id": "pec:duele",
        "shortLabel": "¿Duele?",
        "question": "¿El tratamiento duele?",
        "answer": [
          "Generalmente el tratamiento es muy bien tolerado 🙌",
          "La sensación puede variar según sensibilidad y zona tratada, pero la mayoría de los pacientes lo describen como molestias leves y rápidas."
        ]
      },
      {
        "id": "pec:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones suelen hacerse?",
        "answer": [
          "La cantidad de sesiones (4 a 6) depende de:\n• cantidad de pigmentación\n• profundidad\n• exposición solar\n• y respuesta individual de la piel.\n\nMuchos pacientes observan cambios progresivos desde las primeras sesiones."
        ]
      },
      {
        "id": "pec:verano",
        "shortLabel": "¿En verano?",
        "question": "¿Se puede hacer en verano?",
        "answer": [
          "Depende del grado de exposición solar y del estado actual de la piel.\n\nEn muchos casos pueden realizarse protocolos adaptados, siempre acompañados de protección solar adecuada y cuidados posteriores."
        ]
      },
      {
        "id": "pec:isotretinoina",
        "shortLabel": "¿Si tomo Isotretinoína?",
        "question": "¿Si tomo Isotretinoína / medicamentos me lo puedo hacer?",
        "answer": [
          "¡Sí, perfectamente! 🩺\n\nGracias a que en Corpo Bello contamos con tecnología láser médica premium de última generación (como *Picosure*), el estímulo sobre la piel es fotomecánico y ultra veloz, no térmico.\n\nEsto significa que, a diferencia de los láseres antiguos o agresivos como el láser CO2, es 100% seguro realizarlo si estás tomando *Isotretinoína (Roacután)* u otros medicamentos: el Dr. calibra los parámetros exactos y seguros para tu condición actual.\n\n⚠️ Lo único que te pedimos es que si estás usando ácidos fuertes en crema o antibióticos, los consignes en la historia clínica al realizar la sesión, para darte las indicaciones previas."
        ]
      },
      {
        "id": "pec:vuelta_actividades",
        "shortLabel": "¿Vuelvo a mi rutina?",
        "question": "¿Puedo volver a mis actividades ya mismo?",
        "answer": [
          "¡Sí, absolutamente de inmediato! Al ser una tecnología médica ultra precisa y avanzada, la piel no se quema, no se ampolla ni genera costras agresivas como el Láser CO2.",
          "Al salir del consultorio podés volver a trabajar, estudiar o hacer tu rutina normal. Lo único que podés llegar a notar es un enrojecimiento muy sutil y temporario que desaparece a los pocos minutos, el cual podés cubrir con protector solar con color o maquillaje sin ningún inconveniente."
        ]
      }
    ]
  },
  {
    "slug": "rosacea",
    "displayName": "Rosácea",
    "isGlobal": false,
    "entries": [
      {
        "id": "ros:empeorar",
        "shortLabel": "¿Puede empeorarla?",
        "question": "¿El láser puede empeorar la rosácea?",
        "answer": [
          "Si se utilizan protocolos demasiado agresivos o mal indicados, algunos tratamientos pueden aumentar inflamación o sensibilidad.",
          "👨‍⚕️ Por eso trabajamos ajustando cuidadosamente los parámetros según:\n• sensibilidad\n• vascularización\n• inflamación\n• y respuesta individual de cada piel."
        ]
      },
      {
        "id": "ros:enrojecimiento",
        "shortLabel": "¿Sirve p/ rojez?",
        "question": "¿Sirve para enrojecimiento?",
        "answer": [
          "Sí 🙌\n\nDependiendo del tipo de rosácea y del componente vascular, muchos pacientes observan mejoras progresivas en:\n• rojez\n• lesiones\n• textura\n• y uniformidad de la piel."
        ]
      },
      {
        "id": "ros:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones suelen hacerse?",
        "answer": [
          "La cantidad de sesiones (entre 6 a 8) depende de:\n• intensidad del enrojecimiento\n• sensibilidad\n• componente vascular\n• evolución\n• y respuesta individual.\n\nMuchos pacientes observan cambios progresivos con protocolos láser personalizados."
        ]
      },
      {
        "id": "ros:cura",
        "shortLabel": "¿Tiene cura?",
        "question": "¿La rosácea tiene cura definitiva?",
        "answer": [
          "La rosácea suele ser una condición crónica y sensible, por lo que el objetivo del tratamiento es ayudar a mejorar y controlar progresivamente los síntomas y brotes.",
          "También es importante acompañar el tratamiento con cuidados adecuados y control de factores desencadenantes."
        ]
      },
      {
        "id": "ros:sensible",
        "shortLabel": "¿Piel sensible?",
        "question": "¿Puedo hacerme el tratamiento si tengo la piel muy sensible?",
        "answer": [
          "Sí 👍\n\nJustamente muchos pacientes con rosácea presentan sensibilidad aumentada.",
          "👨‍⚕️ Por eso evaluamos cada caso de forma personalizada antes de indicar parámetros y protocolos, priorizando siempre la seguridad y tolerancia de la piel."
        ]
      },
      {
        "id": "ros:isotretinoina",
        "shortLabel": "¿Si tomo Isotretinoína?",
        "question": "¿Si tomo Isotretinoína / medicamentos me lo puedo hacer?",
        "answer": [
          "¡Sí, perfectamente! 🩺\n\nGracias a que en Corpo Bello contamos con tecnología láser médica premium de última generación (como *Picosure*), el estímulo sobre la piel es fotomecánico y ultra veloz, no térmico.\n\nEsto significa que, a diferencia de los láseres antiguos o agresivos como el láser CO2, es 100% seguro realizarlo si estás tomando *Isotretinoína (Roacután)* u otros medicamentos: el Dr. calibra los parámetros exactos y seguros para tu condición actual.\n\n⚠️ Lo único que te pedimos es que si estás usando ácidos fuertes en crema o antibióticos, los consignes en la historia clínica al realizar la sesión, para darte las indicaciones previas."
        ]
      },
      {
        "id": "ros:vuelta_actividades",
        "shortLabel": "¿Vuelvo a mi rutina?",
        "question": "¿Puedo volver a mis actividades ya mismo?",
        "answer": [
          "¡Sí, absolutamente de inmediato! Al ser una tecnología médica ultra precisa y avanzada, la piel no se quema, no se ampolla ni genera costras agresivas como el Láser CO2.",
          "Al salir del consultorio podés volver a trabajar, estudiar o hacer tu rutina normal. Lo único que podés llegar a notar es un enrojecimiento muy sutil y temporario que desaparece a los pocos minutos, el cual podés cubrir con protector solar con color o maquillaje sin ningún inconveniente."
        ]
      }
    ]
  },
  {
    "slug": "rejuvenecimiento-facial",
    "displayName": "Rejuvenec. facial láser",
    "isGlobal": false,
    "entries": [
      {
        "id": "rej:arrugas",
        "shortLabel": "¿Arrugas y líneas?",
        "question": "¿Sirve para arrugas superficiales y líneas finas?",
        "answer": [
          "Sí 👍\n\nMuchos pacientes realizan rejuvenecimiento con tecnología PicoSure buscando mejorar:\n• líneas finas\n• textura\n• calidad de piel\n• poros\n• y signos iniciales de envejecimiento."
        ]
      },
      {
        "id": "rej:natural",
        "shortLabel": "¿Queda natural?",
        "question": "¿La piel queda natural?",
        "answer": [
          "Sí 🙌\n\nNuestro objetivo no es cambiar la expresión del rostro ni generar un aspecto artificial, sino ayudar a mejorar progresivamente la calidad y apariencia de la piel manteniendo naturalidad."
        ]
      },
      {
        "id": "rej:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones suelen hacerse?",
        "answer": [
          "La cantidad de sesiones depende de:\n• calidad de piel\n• edad\n• objetivos\n• y respuesta individual de cada paciente.\n\nMuchos pacientes observan mejoras progresivas desde las primeras sesiones realizadas con tecnología PicoSure Focus."
        ]
      },
      {
        "id": "rej:combinable",
        "shortLabel": "Combinable con Endolift",
        "question": "¿Se puede combinar con Endolift?",
        "answer": [
          "Sí.\n\nDependiendo de cada caso, los protocolos pueden complementarse con *Endolift* para trabajar distintos planos de la piel y potenciar resultados.",
          "👨‍⚕️ Tenemos muy buenos resultados cuando los tratamientos láser de rejuvenecimiento se combinan con Endolift."
        ]
      },
      {
        "id": "rej:vuelta_actividades",
        "shortLabel": "¿Vuelvo a mi rutina?",
        "question": "¿Puedo volver a mis actividades ya mismo?",
        "answer": [
          "¡Sí, absolutamente de inmediato! Al ser una tecnología médica ultra precisa y avanzada, la piel no se quema, no se ampolla ni genera costras agresivas como el Láser CO2.",
          "Al salir del consultorio podés volver a trabajar, estudiar o hacer tu rutina normal. Lo único que podés llegar a notar es un enrojecimiento muy sutil y temporario que desaparece a los pocos minutos, el cual podés cubrir con protector solar con color o maquillaje sin ningún inconveniente."
        ]
      },
      {
        "id": "rej:isotretinoina",
        "shortLabel": "¿Si tomo Isotretinoína?",
        "question": "¿Si tomo Isotretinoína / medicamentos me lo puedo hacer?",
        "answer": [
          "¡Sí, perfectamente! 🩺\n\nGracias a que en Corpo Bello contamos con tecnología láser médica premium de última generación (como *Picosure*), el estímulo sobre la piel es fotomecánico y ultra veloz, no térmico.\n\nEsto significa que, a diferencia de los láseres antiguos o agresivos como el láser CO2, es 100% seguro realizarlo si estás tomando *Isotretinoína (Roacután)* u otros medicamentos: el Dr. calibra los parámetros exactos y seguros para tu condición actual.\n\n⚠️ Lo único que te pedimos es que si estás usando ácidos fuertes en crema o antibióticos, los consignes en la historia clínica al realizar la sesión, para darte las indicaciones previas."
        ]
      },
      {
        "id": "rej:edad",
        "shortLabel": "¿A qué edad empezar?",
        "question": "¿A qué edad conviene empezar?",
        "answer": [
          "No existe una edad exacta.",
          "Muchos pacientes comienzan tratamientos de rejuvenecimiento buscando prevenir o mejorar progresivamente signos iniciales de envejecimiento y calidad de piel."
        ]
      }
    ]
  },
  {
    "slug": "corporales",
    "displayName": "Tratamientos Corporales",
    "isGlobal": false,
    "entries": [
      {
        "id": "cor:personalizados",
        "shortLabel": "¿Personalizados?",
        "question": "¿Los tratamientos son personalizados?",
        "answer": [
          "Sí 👨‍⚕️\n\nLos protocolos se adaptan según: la historia clínica del paciente, las lesiones que presente, y lo que vamos a mejorar.",
          "El día de la sesión, previamente vas a llenar una historia clínica, y vas a tener una consulta donde nuestro médico te va a explicar de qué se trata el mismo, y los cuidados antes, durante y después de la sesión.\n\nPor eso no todos los pacientes realizan el mismo tratamiento."
        ]
      },
      {
        "id": "cor:consulta",
        "shortLabel": "¿Necesito consulta?",
        "question": "¿Necesito consulta previa?",
        "answer": [
          "En muchos casos podemos orientarte inicialmente mediante fotos para evaluar la zona, explicarte las alternativas posibles de tratamiento y brindarte un presupuesto. El día de la sesión vas a tener una consulta previa con nuestro médico donde te vas a sacar todas las dudas que surjan."
        ]
      },
      {
        "id": "cor:combinar",
        "shortLabel": "¿Combinables?",
        "question": "¿Se pueden combinar tratamientos?",
        "answer": [
          "Sí 🙌\n\nDependiendo de cada caso, algunos pacientes realizan:\n• tratamientos no invasivos o de primera línea\n• protocolos avanzados Premium\n• o tratamientos combinados para potenciar resultados."
        ]
      },
      {
        "id": "cor:cambios",
        "shortLabel": "¿Cuándo se ven?",
        "question": "¿Cuándo suelen empezar a verse cambios?",
        "answer": [
          "Depende del tratamiento realizado, la zona y las características de cada paciente.",
          "Muchos pacientes observan mejoras progresivas en textura, calidad de piel y contorno corporal a medida que avanzan las sesiones."
        ]
      }
    ]
  },
  {
    "slug": "foliculitis-gluteos",
    "displayName": "Foliculitis corporal",
    "isGlobal": false,
    "entries": [
      {
        "id": "fol:vs_depilacion",
        "shortLabel": "¿Como depilación común?",
        "question": "¿Es el mismo láser que una depilación común?",
        "answer": [
          "No.\n\nMuchas personas llegan después de realizar múltiples sesiones de depilación láser sin mejorar realmente la foliculitis.",
          "👨‍⚕️ Porque un láser de depilación tradicional puede ayudar a reducir el vello, pero muchas veces no alcanza para mejorar:\n• manchas\n• inflamación\n• lesiones recurrentes\n• irritación\n• y secuelas asociadas a la foliculitis.",
          "Por eso en Corpo Bello utilizamos distintas tecnologías y protocolos personalizados según cada paciente y el problema predominante de la piel. Incluso podemos combinar diferentes tecnologías láser para llegar a los resultados esperados."
        ]
      },
      {
        "id": "fol:volver",
        "shortLabel": "¿Puede volver?",
        "question": "¿La foliculitis puede volver?",
        "answer": [
          "Sí.\n\nMuchas veces la foliculitis está relacionada con:\n• depilación\n• roce\n• sudor\n• inflamación\n• pelos encarnados\n• o predisposición de la piel.\n\nPor eso el objetivo es ayudar a controlar progresivamente los brotes y mejorar la calidad de la piel."
        ]
      },
      {
        "id": "fol:manchas",
        "shortLabel": "¿Para manchas?",
        "question": "¿Sirve para manchas y marcas?",
        "answer": [
          "Sí 🙌\n\nMuchos pacientes además observan mejora en:\n• manchas\n• marcas\n• textura\n• e irritación residual asociada a la foliculitis."
        ]
      },
      {
        "id": "fol:zonas",
        "shortLabel": "¿Qué zonas?",
        "question": "¿Qué zonas pueden tratarse?",
        "answer": [
          "Dependiendo de cada caso, pueden tratarse zonas como:\n• glúteos\n• piernas\n• ingles\n• barba\n• axilas\n• espalda\n• y otras áreas corporales."
        ]
      },
      {
        "id": "fol:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones suelen hacerse?",
        "answer": [
          "La cantidad de sesiones depende de:\n• inflamación\n• extensión\n• recurrencia\n• tipo de piel\n• y evolución individual.\n\nMuchos pacientes observan mejoras progresivas a medida que avanzan las sesiones. Se necesitan aproximadamente 6-8 sesiones, una vez por mes."
        ]
      },
      {
        "id": "fol:depilacion_empeora",
        "shortLabel": "¿Depilación empeora?",
        "question": "¿La depilación empeora la foliculitis?",
        "answer": [
          "Algunos métodos depilatorios como maquinitas de afeitar y la cera pueden empeorar irritación y pelos encarnados en pacientes predispuestos.",
          "👨‍⚕️ Por eso es importante evaluar cada caso y adaptar el tratamiento según la piel y la zona afectada."
        ]
      }
    ]
  },
  {
    "slug": "manchas-blanqueamiento",
    "displayName": "Blanqueamiento corporal",
    "isGlobal": false,
    "entries": [
      {
        "id": "bla:zonas",
        "shortLabel": "¿Qué zonas?",
        "question": "¿Qué zonas pueden tratarse?",
        "answer": [
          "Dependiendo de cada caso, pueden tratarse zonas como:\n• axilas\n• cavado\n• entrepierna\n• tira de cola\n• rodillas\n• codos\n• y otras áreas corporales con hiperpigmentación."
        ]
      },
      {
        "id": "bla:volver",
        "shortLabel": "¿Pueden volver?",
        "question": "¿Las manchas pueden volver?",
        "answer": [
          "Sí.\n\nMuchas veces la pigmentación está relacionada con:\n• roce\n• inflamación\n• depilación\n• hormonas\n• sudoración\n• y predisposición de la piel.\n\nPor eso el objetivo es mejorar progresivamente la pigmentación y acompañar el tratamiento con cuidados adecuados."
        ]
      },
      {
        "id": "bla:duele",
        "shortLabel": "¿Duele?",
        "question": "¿Es doloroso?",
        "answer": [
          "Generalmente los tratamientos son bien tolerados 🙌\n\nLa sensación puede variar según:\n• sensibilidad\n• zona tratada\n• y protocolo utilizado."
        ]
      },
      {
        "id": "bla:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones suelen hacerse?",
        "answer": [
          "La cantidad de sesiones (entre 6 a 8) depende de:\n• profundidad de la pigmentación\n• zona\n• sensibilidad\n• y evolución individual de cada paciente.\n\nMuchos pacientes observan mejoras progresivas a medida que avanzan las sesiones."
        ]
      }
    ]
  },
  {
    "slug": "verrugas-lunares",
    "displayName": "Verrugas y lunares",
    "isGlobal": false,
    "entries": [
      {
        "id": "vrg:tipos",
        "shortLabel": "¿Qué lesiones trata?",
        "question": "¿Qué tipo de lesiones pueden tratarse?",
        "answer": [
          "Dependiendo de cada caso, pueden evaluarse lesiones como:\n• verrugas\n• acrocordomas\n• lunares elevados\n• pequeñas lesiones benignas y fibromas\n• y otras alteraciones cutáneas superficiales."
        ]
      },
      {
        "id": "vrg:duele",
        "shortLabel": "¿Duele?",
        "question": "¿Duele el tratamiento?",
        "answer": [
          "La molestia depende de:\n• la zona\n• tamaño\n• cantidad de lesiones\n• y tratamiento realizado.\n\nEn muchos casos se utilizan métodos para mejorar la tolerancia y comodidad del procedimiento, como anestesia en crema, o nuestro médico puede infiltrar la zona con anestesia local."
        ]
      },
      {
        "id": "vrg:volver",
        "shortLabel": "¿Pueden volver?",
        "question": "¿Las lesiones pueden volver?",
        "answer": [
          "Depende del tipo de lesión y de cada paciente.\n\nAlgunas lesiones pueden reaparecer o aparecer nuevas con el tiempo dependiendo de predisposición, roce, piel y otros factores. Por eso se recomienda una o dos sesiones cada 3 meses por si la lesión vuelve."
        ]
      },
      {
        "id": "vrg:marcas",
        "shortLabel": "¿Quedan marcas?",
        "question": "¿Quedan marcas?",
        "answer": [
          "La evolución depende de:\n• tipo de lesión\n• profundidad\n• ubicación\n• tamaño\n• y características individuales de la piel.\n\nPor eso cada caso se evalúa de forma personalizada antes de indicar tratamiento."
        ]
      },
      {
        "id": "vrg:foto_previa",
        "shortLabel": "¿Enviar foto antes?",
        "question": "¿Puedo enviar foto antes de reservar?",
        "answer": [
          "Sí 👍\n\nPodés enviar una foto de la lesión para poder orientarte inicialmente sobre las alternativas posibles de tratamiento y el precio aproximado."
        ]
      }
    ]
  },
  {
    "slug": "onicomicosis",
    "displayName": "Onicomicosis",
    "isGlobal": false,
    "entries": [
      {
        "id": "oni:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones se realizan?",
        "answer": [
          "La cantidad de sesiones depende de:\n• cantidad de uñas afectadas\n• grado de compromiso\n• tiempo de evolución\n• y respuesta individual de cada paciente.",
          "📅 Se realiza 1 sesión por semana.\n\nTambién contamos con *promoción 5x4*: abonás 4 sesiones y realizás 5."
        ]
      },
      {
        "id": "oni:duele",
        "shortLabel": "¿Duele?",
        "question": "¿Duele?",
        "answer": [
          "Generalmente es muy bien tolerado.\n\nPuede sentirse calor en la uña durante la aplicación del láser, pero suele ser una molestia breve y tolerable."
        ]
      },
      {
        "id": "oni:cambios",
        "shortLabel": "¿Cuándo se ven?",
        "question": "¿Cuándo se ven los cambios?",
        "answer": [
          "La uña no cambia de un día para el otro.",
          "Los cambios suelen verse progresivamente a medida que la uña crece nueva y saludable.\n\nPor eso es importante tener paciencia y completar el protocolo indicado."
        ]
      },
      {
        "id": "oni:afectada",
        "shortLabel": "¿Uña muy afectada?",
        "question": "¿Sirve si la uña está muy afectada?",
        "answer": [
          "Depende del grado de compromiso de la uña.\n\nPor eso pedimos una foto clara para poder orientarte mejor y evaluar si el tratamiento láser es una buena alternativa para tu caso."
        ]
      },
      {
        "id": "oni:foto",
        "shortLabel": "¿Necesito foto?",
        "question": "¿Necesito enviar foto?",
        "answer": [
          "Sí.\n\nPara poder orientarte correctamente necesitamos una foto clara de la uña o uñas afectadas, con buena luz y sin esmalte."
        ]
      }
    ]
  },
  {
    "slug": "endolift",
    "displayName": "Endolift",
    "isGlobal": false,
    "entries": [
      {
        "id": "end:duele",
        "shortLabel": "¿Duele?",
        "question": "¿Duele el tratamiento?",
        "answer": [
          "No, para nada. Se utiliza anestesia local en la zona a tratar para que el procedimiento sea totalmente confortable, seguro y libre de dolor durante la sesión."
        ]
      },
      {
        "id": "end:recuperacion",
        "shortLabel": "¿Recuperación?",
        "question": "¿Cómo es la recuperación?",
        "answer": [
          "La recuperación es mínima. Al ser un procedimiento ambulatorio, podés volver a tus actividades habituales casi de inmediato. Solo se puede presentar una leve inflamación o rojez que desaparece por completo en unos pocos días."
        ]
      },
      {
        "id": "end:imitaciones",
        "shortLabel": "⚠️ Imitaciones",
        "question": "⚠️ Alerta sobre imitaciones y precios",
        "answer": [
          "Esta es la pregunta más importante que tenés que hacerte. 🚨\n\nEn el mercado existen clínicas que ofrecen \"combos de 5 zonas\" a precios sospechosamente bajos. Queremos advertirte que suelen trabajar con equipos de imitación chinos, sin aprobaciones de ANMAT, o con longitudes de onda no controladas.",
          "Al ser un procedimiento donde se introduce una microfibra bajo la piel, un equipo sin precisión médica o mal calibrado tiene un riesgo altísimo de causar quemaduras internas severas, necrosis de la piel o fibrosis deformantes irreversibles. Lo barato puede costar muy caro cuando se trata de tu salud.",
          "👨‍⚕️ En Corpo Bello te garantizamos máxima seguridad: trabajamos exclusivamente con la plataforma original *Endolift Eufoton (Italia)* habilitada por ANMAT. El procedimiento lo realiza de principio a fin el Dr. Andrés Bejarano bajo estrictas normas de asepsia."
        ]
      },
      {
        "id": "end:duracion_efecto",
        "shortLabel": "¿Cuánto dura?",
        "question": "¿Cuánto dura el efecto?",
        "answer": [
          "Los resultados son a largo plazo y sumamente duraderos. El láser destruye la grasa localizada de forma permanente y genera una reestructuración de colágeno profunda que sigue mejorando hasta 6 a 8 meses después de la sesión.\n\nEl efecto de tensado y rejuvenecimiento suele durar varios años, acompañando el proceso natural de la piel y según el cuidado nutricional del paciente."
        ]
      },
      {
        "id": "end:duracion_sesion",
        "shortLabel": "¿Cuánto tarda?",
        "question": "¿Cuánto tarda la sesión?",
        "answer": [
          "Es un procedimiento rápido. Dependiendo de la cantidad de zonas a tratar, la sesión en el consultorio dura entre 45 y 90 minutos en total. Al terminar, te vas a tu casa por tu cuenta sin ningún tipo de complicación."
        ]
      },
      {
        "id": "end:verano",
        "shortLabel": "¿En verano?",
        "question": "¿Se puede hacer en verano?",
        "answer": [
          "¡Sí, totalmente! Al ser una tecnología que trabaja de forma interna (subdérmica) a través de una microfibra óptica, la superficie de la piel no queda dañada ni expuesta como con los láseres tradicionales. Se puede realizar en cualquier época del año, incluso en verano, cuidando la zona con protector solar diario."
        ]
      },
      {
        "id": "end:rostro_cuello",
        "shortLabel": "Rostro y cuello",
        "question": "¿Qué puede mejorar Endolift en rostro y cuello?",
        "answer": [
          "Endolift es uno de los tratamientos más avanzados para *redefinir el contorno facial sin cirugía*.\n\nPermite tensar la piel, mejorar la flacidez, reducir papada y redefinir la línea mandibular mediante una microfibra láser que trabaja debajo de la piel estimulando colágeno y actuando también sobre pequeños depósitos grasos."
        ]
      },
      {
        "id": "end:adiposidad_celulitis",
        "shortLabel": "Adiposidad y celulitis",
        "question": "¿Cómo actúa Endolift en adiposidad y celulitis?",
        "answer": [
          "En el cuerpo, Endolift ayuda a tensar piel flácida y reducir adiposidad localizada en zonas difíciles como abdomen, brazos, piernas, entrepiernas y glúteos.\n\nAdemás, mediante *subcisión láser* mejora la piel de naranja y la celulitis actuando sobre los tabiques fibrosos que generan el poceado."
        ]
      },
      {
        "id": "end:cicatrices",
        "shortLabel": "Cicatrices acné/fibrosas",
        "question": "¿Sirve para cicatrices de acné o cicatrices fibrosas?",
        "answer": [
          "Sí. Endolift realiza una *subcisión láser* debajo de la cicatriz liberando fibrosis internas y estimulando colágeno nuevo desde profundidad.\n\nEsto ayuda a mejorar cicatrices hundidas de acné, cicatrices quirúrgicas o secuelas fibrosas en distintas zonas del cuerpo."
        ]
      },
      {
        "id": "end:ubicacion",
        "shortLabel": "Ubicación y horarios",
        "question": "¿Dónde se realiza el tratamiento de Endolift?",
        "answer": [
          "Endolift se realiza en nuestros consultorios médicos de:\n\n📍 *Caballito (CABA)*\n• Dos jueves al mes de 14 a 20 hs\n• y un sábado al mes de 14 a 20 hs\n\n📍 *Merlo*\n• Martes de 9 a 20 hs\n\n⚠️ En la sede de Moreno solo realizamos depilación láser Soprano Ice.\n\n👉 Los turnos son únicamente con reserva previa."
        ]
      }
    ]
  },
  {
    "slug": "laserpeel",
    "displayName": "Laserpeel",
    "isGlobal": false,
    "entries": [
      {
        "id": "lpl:duele",
        "shortLabel": "¿Duele?",
        "question": "¿Duele el tratamiento?",
        "answer": [
          "No, para nada. Es un tratamiento totalmente indoloro. Solo vas a sentir una leve sensación de calorcito muy agradable sobre la piel. Es un procedimiento sumamente confortable, rápido y seguro."
        ]
      },
      {
        "id": "lpl:recuperacion",
        "shortLabel": "¿Recuperación?",
        "question": "¿Cómo es la recuperación?",
        "answer": [
          "¡Es inmediata! Al terminar la sesión tu piel puede quedar con un leve tono rosado que desaparece en menos de una hora.\n\nNo genera costras ni descamación agresiva, por lo que podés maquillarte y volver a tus actividades al salir del consultorio."
        ]
      },
      {
        "id": "lpl:cadencia",
        "shortLabel": "¿Cada cuánto?",
        "question": "¿Cada cuánto se hace?",
        "answer": [
          "Vas a notar un cambio espectacular en la textura y el brillo de tu piel desde la primera sesión.\n\nSegún los objetivos de tu piel (manchas, acné o rejuvenecimiento), el Dr. suele recomendar un protocolo de 4 a 6 sesiones, espaciadas cada 28-30 días para lograr resultados acumulativos y duraderos."
        ]
      },
      {
        "id": "lpl:carbon",
        "shortLabel": "¿Por qué no carbón?",
        "question": "¿Por qué NO usan carbón negro?",
        "answer": [
          "Esta es nuestra mayor diferencia médica. 🩺\n\nEl tratamiento es mundialmente conocido como *Hollywood Peel* o *Laserpeel* porque muchos centros estéticos aplican una máscara de carbón negro que visualmente es muy llamativa para las redes sociales, teniendo un fin netamente marketinero.",
          "Sin embargo, médicamente el carbón es un error: cuando el láser choca contra la capa negra, el carbón absorbe y disipa la mayor parte de la energía en el aire. Como resultado, a la piel le llega muchísima menos potencia de la que realmente necesita para cambiar.",
          "👨‍⚕️ En Corpo Bello mantenemos el nombre Laserpeel pero priorizamos la efectividad real por encima del marketing. Aplicamos la tecnología láser directamente sobre tu piel limpia, garantizando que el 100% de la energía llegue con total pureza a las capas profundas. Por eso nuestros resultados son tan superiores desde la primera sesión."
        ]
      },
      {
        "id": "lpl:verano",
        "shortLabel": "¿En verano?",
        "question": "¿Se puede en verano?",
        "answer": [
          "¡Sí, totalmente! Al ser un láser de tecnología avanzada que no agrede la capa superficial de la epidermis (no la quema ni la lija), no sensibiliza la piel ante el sol de forma extrema.\n\nSe puede realizar de forma segura durante todo el año, cuidándote con protector solar diario como de costumbre."
        ]
      },
      {
        "id": "lpl:imitaciones",
        "shortLabel": "⚠️ Imitaciones",
        "question": "⚠️ Alerta sobre equipos de imitación",
        "answer": [
          "🚨 Queremos advertirte que en el mercado abundan lugares que ofrecen tecnologías láser utilizando réplicas chinas o equipos estéticos sin aprobaciones sanitarias. Un láser mal calibrado puede causar quemaduras reales, manchas oscuras permanentes o daño ocular.\n\n👨‍⚕️ En Corpo Bello tu salud es lo primero: trabajamos exclusivamente con plataformas láser médicas de alta gama (*Picosure* y Revlite), legalmente habilitadas por ANMAT."
        ]
      },
      {
        "id": "lpl:isotretinoina",
        "shortLabel": "¿Si tomo Isotretinoína?",
        "question": "¿Si tomo Isotretinoína / medicamentos me lo puedo hacer?",
        "answer": [
          "¡Sí, perfectamente! 🩺\n\nGracias a que en Corpo Bello contamos con tecnología láser médica premium de última generación (como *Picosure*), el estímulo sobre la piel es fotomecánico y ultra veloz, no térmico.\n\nEsto significa que, a diferencia de los láseres antiguos o agresivos como el láser CO2, es 100% seguro realizarlo si estás tomando *Isotretinoína (Roacután)* u otros medicamentos: el Dr. calibra los parámetros exactos y seguros para tu condición actual.\n\n⚠️ Lo único que te pedimos es que si estás usando ácidos fuertes en crema o antibióticos, los consignes en la historia clínica al realizar la sesión, para darte las indicaciones previas."
        ]
      },
      {
        "id": "lpl:vuelta_actividades",
        "shortLabel": "¿Vuelvo a mi rutina?",
        "question": "¿Puedo volver a mis actividades ya mismo?",
        "answer": [
          "¡Sí, absolutamente de inmediato! Al ser una tecnología médica ultra precisa y avanzada, la piel no se quema, no se ampolla ni genera costras agresivas como el Láser CO2.",
          "Al salir del consultorio podés volver a trabajar, estudiar o hacer tu rutina normal. Lo único que podés llegar a notar es un enrojecimiento muy sutil y temporario que desaparece a los pocos minutos, el cual podés cubrir con protector solar con color o maquillaje sin ningún inconveniente."
        ]
      }
    ]
  },
  {
    "slug": "cicatrices",
    "displayName": "Cicatrices Hiperpigm.",
    "isGlobal": false,
    "entries": [
      {
        "id": "cic:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones lleva?",
        "answer": [
          "Al tratarse de un proceso biológico donde tu cuerpo debe eliminar el pigmento pulverizado, los resultados son graduales.\n\nPor lo general, se recomiendan entre 3 y 6 sesiones (espaciadas cada 21 o 30 días). El número exacto dependerá de la antigüedad y la profundidad de la mancha."
        ]
      },
      {
        "id": "cic:duele",
        "shortLabel": "¿Duele?",
        "question": "¿El tratamiento duele?",
        "answer": [
          "No es doloroso. Se siente un pequeño chasquido y una sensación de calor local muy tolerable en la zona de la cicatriz. El procedimiento es rápido y seguro."
        ]
      },
      {
        "id": "cic:descama",
        "shortLabel": "¿Se descama?",
        "question": "¿La piel se descama?",
        "answer": [
          "No genera costras ni descamaciones agresivas. La zona puede quedar ligeramente rosada o un poco más oscura durante los primeros días (lo cual es normal porque el pigmento sube a la superficie) y luego se va aclarando. Podés continuar con tu rutina normal de inmediato."
        ]
      },
      {
        "id": "cic:verano",
        "shortLabel": "¿En verano?",
        "question": "¿Se puede hacer en verano?",
        "answer": [
          "Sí, se puede realizar. Pero al estar tratando una zona con tendencia a mancharse, el uso de protector solar 50+ cada 2 o 3 horas en la cicatriz es estrictamente obligatorio e innegociable para evitar que el sol vuelva a oscurecer el pigmento."
        ]
      },
      {
        "id": "cic:imitaciones",
        "shortLabel": "⚠️ Imitaciones",
        "question": "⚠️ Alerta sobre equipos de imitación",
        "answer": [
          "🚨 Advertencia médica importante:\n\nTratar una cicatriz hiperpigmentada con un láser de estética de baja calidad o mal calibrado puede generar el efecto opuesto: una quemadura térmica que empeore drásticamente la mancha (hiperpigmentación rebote).\n\n👨‍⚕️ En Corpo Bello trabajamos con plataformas láser médicas premium aprobadas por ANMAT — principalmente *Picosure* (uno de los pocos equipos originales en Argentina) y complementariamente Revlite cuando el criterio profesional lo indica — para garantizar la máxima seguridad y resultados de tu piel."
        ]
      }
    ]
  },
  {
    "slug": "microblading",
    "displayName": "Microblading + derm.",
    "isGlobal": false,
    "entries": [
      {
        "id": "mic:quema_pelos",
        "shortLabel": "¿Quema los pelos?",
        "question": "¿El láser me va a quemar o desprender los pelos de la ceja?",
        "answer": [
          "¡Para nada! 🩺 Esta es la duda más frecuente y el mayor miedo de los pacientes.",
          "Al trabajar con tecnología láser médica de picosegundos, el disparo actúa por un efecto fotomecánico (vibración ultrasónica ultra veloz) que destruye el pigmento artificial de la tinta sin generar calor extremo.",
          "Esto garantiza que el folículo piloso de tus cejas quede completamente intacto y protegido. Tus pelitos naturales no se van a caer ni a dañar."
        ]
      },
      {
        "id": "mic:cambio_color",
        "shortLabel": "¿Cambia de color?",
        "question": "¿Es normal que la tinta cambie de color después de la sesión?",
        "answer": [
          "Sí, es un proceso perfectamente normal y clínicamente esperable.",
          "Las tintas de microblading o dermopigmentación suelen ser mezclas de varios colores (marrón, negro, rojo, amarillo). A medida que el láser destruye los pigmentos más oscuros, la zona puede pasar temporalmente por tonos rojizos, grisáceos o anaranjados antes de aclararse por completo.",
          "Nuestro láser cuenta con diferentes longitudes de onda para ir eliminando cada uno de esos colores residuales de forma segura en las siguientes sesiones."
        ]
      },
      {
        "id": "mic:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones se necesitan para borrar unas cejas?",
        "answer": [
          "Al ser un pigmento depositado a nivel muy superficial (a diferencia de un tatuaje corporal), por lo general requiere menos sesiones.",
          "El promedio suele ser entre *2 y 4 sesiones* para un aclarado óptimo o eliminación completa.",
          "El número exacto va a depender de la antigüedad del trabajo, la cantidad de retoques que te hayas hecho y la calidad de la tinta que usó el tatuador."
        ]
      },
      {
        "id": "mic:hinchazon",
        "shortLabel": "¿Hinchan los párpados?",
        "question": "¿Se pueden hinchar los párpados o la zona de los ojos?",
        "answer": [
          "Es una reacción posible, pero sumamente leve y temporaria. Al tratarse de una zona con piel muy delgada y sensible, es completamente normal que notes una mínima inflamación o un ligero edema en los párpados inmediatamente después de la sesión.",
          "Esta respuesta biológica es sutil y desaparece por completo por sí sola en las primeras *24 a 48 horas*.\n\nPara acelerar el proceso y que estés súper confortable, te indicamos aplicar frío local seco durante el primer día."
        ]
      },
      {
        "id": "mic:actividades",
        "shortLabel": "¿Vuelvo a mi rutina?",
        "question": "¿Puedo volver a mis actividades normales después de la sesión?",
        "answer": [
          "¡Sí, al salir del consultorio podés continuar con tu rutina habitual! Al no ser un procedimiento quirúrgico ni ablativo, no necesitás hacer reposo ni faltar al trabajo.",
          "Lo único que vas a notar es la zona un poco rosada y la tinta en pleno proceso de cambio. Te pedimos:\n• evitar el sol directo\n• no realizar actividad física intensa (que te haga transpirar mucho)\n• no usar maquillaje directamente sobre la ceja durante los primeros 3 a 5 días\n\nasí garantizamos una curación impecable."
        ]
      }
    ]
  },
  {
    "slug": "venus-legacy",
    "displayName": "Venus Legacy",
    "isGlobal": false,
    "entries": [
      {
        "id": "vl:que_es",
        "shortLabel": "¿Qué es?",
        "question": "¿Qué es Venus Legacy?",
        "answer": [
          "Es un equipo de radiofrecuencia multipolar con campos magnéticos pulsados. Trata celulitis, flaccidez y remodelación corporal de forma no invasiva."
        ]
      },
      {
        "id": "vl:sesiones",
        "shortLabel": "¿Cuántas sesiones?",
        "question": "¿Cuántas sesiones necesito?",
        "answer": [
          "Se recomienda un plan de sesiones según la zona y el objetivo (entre 8 y 10 sesiones). Frecuencia: 1 sesión por semana."
        ]
      },
      {
        "id": "vl:duele",
        "shortLabel": "¿Duele?",
        "question": "¿El tratamiento duele?",
        "answer": [
          "No, es un procedimiento cómodo. Sentís un calor agradable en la zona tratada."
        ]
      }
    ]
  },
  {
    "slug": "sueroterapia",
    "displayName": "Sueroterapia",
    "isGlobal": false,
    "entries": [
      {
        "id": "sue:beneficios",
        "shortLabel": "¿Qué beneficios?",
        "question": "¿Cuáles son los principales beneficios?",
        "answer": [
          "Antioxidante potente, refuerza el sistema inmune, mejora recuperación celular y vitalidad general."
        ]
      },
      {
        "id": "sue:frecuencia",
        "shortLabel": "¿Cada cuánto?",
        "question": "¿Con qué frecuencia se recomienda recibir la sueroterapia?",
        "answer": [
          "Según indicación médica, generalmente semanal o quincenal según necesidades."
        ]
      },
      {
        "id": "sue:duracion",
        "shortLabel": "¿Cuánto dura?",
        "question": "¿Cuánto dura cada sesión?",
        "answer": [
          "Aproximadamente 20 a 40 minutos según la dosis."
        ]
      },
      {
        "id": "sue:combinar",
        "shortLabel": "¿Combinable?",
        "question": "¿Se puede combinar con otros tratamientos estéticos?",
        "answer": [
          "Sí, no hay contraindicaciones."
        ]
      }
    ]
  },
  {
    "slug": "globals",
    "displayName": "General del consultorio",
    "isGlobal": true,
    "entries": [
      {
        "id": "glob:sedes",
        "shortLabel": "¿Dónde están?",
        "question": "¿Dónde están ubicados?",
        "answer": [
          "📍 Contamos con consultorios médicos en:\n• Merlo\n• Caballito\n• Moreno"
        ]
      },
      {
        "id": "glob:turno",
        "shortLabel": "¿Cómo pido turno?",
        "question": "¿Cómo pido un turno?",
        "answer": [
          "Podés realizar la reserva directamente desde este chat 👌",
          "Una vez finalizada la evaluación/cotización, el sistema te va a solicitar un depósito por transferencia para asegurar tu fecha y horario.\n\n📌 La reserva queda confirmada una vez enviado el comprobante.",
          "👉 Todos los turnos son con cita previa y cupos limitados.\n\n⚠️ El depósito se utiliza exclusivamente para la reserva del turno y futuras reservas dentro del tratamiento."
        ]
      },
      {
        "id": "glob:pago",
        "shortLabel": "¿Cómo se paga?",
        "question": "¿Aceptan tarjetas o billeteras virtuales?",
        "answer": [
          "Sí, aceptamos tarjetas de crédito, débito, transferencias, Mercado Pago y billeteras digitales.",
          "💵 Tenemos un *50% de descuento en efectivo* en todos nuestros tratamientos cuando se abona el total el día del turno."
        ]
      },
      {
        "id": "glob:cancelacion",
        "shortLabel": "Cancelación",
        "question": "¿Qué pasa si no voy al turno?",
        "answer": [
          "Si no cancelás con 48 horas de anticipación, el depósito se pierde. Los depósitos no son reembolsables, salvo casos excepcionales de fuerza mayor."
        ]
      }
    ]
  }
]
