// AUTO-GENERATED by the bot repo's scripts/gen-quoting-defaults.mjs — DO NOT EDIT.
// Source of truth: the bot's src/quoting/fixtures.ts.
// Regenerate after editing fixtures: (in the bot repo) npm run build &&
// node scripts/gen-quoting-defaults.mjs
//
// The Cotizador editor renders these defaults; the clinic's saved edits are
// stored (full JSON) in quoting_config and the bot overlays them fail-open.

export interface TattooBand {
  maxCm2: number
  base: number
}

export interface TattooRulesJson {
  type: 'tattoo'
  currency: 'ARS' | 'USD'
  bands: TattooBand[]
  tipoMultiplier: { lineal: number; no_lineal: number }
  colorMultiplier: {
    negro: number
    dos_colores: number
    multicolor: number
    verdes_azules: number
  }
  ubicacionMultiplier: { rostro: number; resto: number }
  linealMinLargoCm: number
  prevSessionsRecargo: number
  alergiaRecargo: number
  multiTatuajeDiscount: number
  multiTatuajeDiscount4plus: number
  efectivoDiscount: number
}

export interface LaserZoneEntry {
  key: string
  label: string
  gender: 'mujer' | 'hombre'
  pricePerSession: number
}

export interface LaserRulesJson {
  type: 'laser'
  currency: 'ARS' | 'USD'
  efectivoDiscount: number
  zones: LaserZoneEntry[]
}

export const TATTOO_DEFAULT: TattooRulesJson = {
  "type": "tattoo",
  "bands": [
    {
      "maxCm2": 3,
      "base": 160000
    },
    {
      "maxCm2": 10,
      "base": 180000
    },
    {
      "maxCm2": 20,
      "base": 190000
    },
    {
      "maxCm2": 30,
      "base": 200000
    },
    {
      "maxCm2": 40,
      "base": 220000
    },
    {
      "maxCm2": 50,
      "base": 260000
    },
    {
      "maxCm2": 70,
      "base": 280000
    },
    {
      "maxCm2": 90,
      "base": 280000
    },
    {
      "maxCm2": 100,
      "base": 340000
    },
    {
      "maxCm2": 110,
      "base": 360000
    },
    {
      "maxCm2": 130,
      "base": 370000
    },
    {
      "maxCm2": 140,
      "base": 380000
    },
    {
      "maxCm2": 150,
      "base": 400000
    },
    {
      "maxCm2": 170,
      "base": 400000
    },
    {
      "maxCm2": 190,
      "base": 440000
    },
    {
      "maxCm2": 210,
      "base": 460000
    },
    {
      "maxCm2": 230,
      "base": 480000
    },
    {
      "maxCm2": 250,
      "base": 550000
    },
    {
      "maxCm2": 280,
      "base": 580000
    },
    {
      "maxCm2": 330,
      "base": 600000
    },
    {
      "maxCm2": 400,
      "base": 660000
    },
    {
      "maxCm2": 700,
      "base": 780000
    }
  ],
  "tipoMultiplier": {
    "lineal": 1.25,
    "no_lineal": 1
  },
  "colorMultiplier": {
    "negro": 1,
    "dos_colores": 1.05,
    "multicolor": 1.1,
    "verdes_azules": 1.15
  },
  "ubicacionMultiplier": {
    "rostro": 1,
    "resto": 1
  },
  "linealMinLargoCm": 7,
  "prevSessionsRecargo": 0.1,
  "alergiaRecargo": 0.1,
  "multiTatuajeDiscount": 0.25,
  "multiTatuajeDiscount4plus": 0.3,
  "efectivoDiscount": 0.5,
  "currency": "ARS"
}

export const LASER_DEFAULT: LaserRulesJson = {
  "type": "laser",
  "currency": "ARS",
  "efectivoDiscount": 0.5,
  "zones": [
    {
      "key": "CAV_COMPL_MUJ",
      "label": "Cavado completo",
      "gender": "mujer",
      "pricePerSession": 54000
    },
    {
      "key": "CAV_SIMPL_MUJ",
      "label": "Cavado simple",
      "gender": "mujer",
      "pricePerSession": 46000
    },
    {
      "key": "LABIOS_MUJ",
      "label": "Labios",
      "gender": "mujer",
      "pricePerSession": 44000
    },
    {
      "key": "CAV_COMP_EXT_MUJ",
      "label": "Cavado comp ext",
      "gender": "mujer",
      "pricePerSession": 66000
    },
    {
      "key": "TIRA_COLA_MUJ",
      "label": "Tira de cola",
      "gender": "mujer",
      "pricePerSession": 46000
    },
    {
      "key": "GLUTEOS_MUJ",
      "label": "Glúteos",
      "gender": "mujer",
      "pricePerSession": 60000
    },
    {
      "key": "AXI_MUJ",
      "label": "Axilas",
      "gender": "mujer",
      "pricePerSession": 52000
    },
    {
      "key": "BRAZOS_MUJ",
      "label": "Brazos completos",
      "gender": "mujer",
      "pricePerSession": 66000
    },
    {
      "key": "ANTEBR_MUJ",
      "label": "Antebrazos",
      "gender": "mujer",
      "pricePerSession": 52000
    },
    {
      "key": "MANOS_MUJ",
      "label": "Manos",
      "gender": "mujer",
      "pricePerSession": 44000
    },
    {
      "key": "PIERNAS_MUJ",
      "label": "Piernas completas",
      "gender": "mujer",
      "pricePerSession": 76000
    },
    {
      "key": "MP_INF_MUJ",
      "label": "Media pierna inferior",
      "gender": "mujer",
      "pricePerSession": 64000
    },
    {
      "key": "MP_SUP_MUJ",
      "label": "Media pierna superior",
      "gender": "mujer",
      "pricePerSession": 68000
    },
    {
      "key": "EMPEINE_MUJ",
      "label": "Empeine",
      "gender": "mujer",
      "pricePerSession": 44000
    },
    {
      "key": "DEDOS_MUJ",
      "label": "Dedos",
      "gender": "mujer",
      "pricePerSession": 44000
    },
    {
      "key": "ESP_BAJA_MUJ",
      "label": "Espalda baja",
      "gender": "mujer",
      "pricePerSession": 62000
    },
    {
      "key": "ESP_ALTA_MUJ",
      "label": "Espalda alta",
      "gender": "mujer",
      "pricePerSession": 66000
    },
    {
      "key": "ESP_SUP_HOMBROS_MUJ",
      "label": "Espalda superior+hombros",
      "gender": "mujer",
      "pricePerSession": 88000
    },
    {
      "key": "ESP_COMP_MUJ",
      "label": "Espalda completa",
      "gender": "mujer",
      "pricePerSession": 78000
    },
    {
      "key": "ABDOMEN_MUJ",
      "label": "Abdomen completo",
      "gender": "mujer",
      "pricePerSession": 66000
    },
    {
      "key": "ROSTRO_MUJ",
      "label": "Rostro",
      "gender": "mujer",
      "pricePerSession": 58000
    },
    {
      "key": "MENTON_MUJ",
      "label": "Mentón",
      "gender": "mujer",
      "pricePerSession": 44000
    },
    {
      "key": "SUBMENTON_MUJ",
      "label": "Submentón",
      "gender": "mujer",
      "pricePerSession": 44000
    },
    {
      "key": "BOZO_MUJ",
      "label": "Bozo",
      "gender": "mujer",
      "pricePerSession": 44000
    },
    {
      "key": "PATILLAS_MUJ",
      "label": "Patillas",
      "gender": "mujer",
      "pricePerSession": 46000
    },
    {
      "key": "MEDIO_ROSTRO_MUJ",
      "label": "Medio rostro",
      "gender": "mujer",
      "pricePerSession": 52000
    },
    {
      "key": "CEJAS_MUJ",
      "label": "Cejas",
      "gender": "mujer",
      "pricePerSession": 46000
    },
    {
      "key": "LINEA_ALBA_MUJ",
      "label": "Línea alba",
      "gender": "mujer",
      "pricePerSession": 46000
    },
    {
      "key": "NUCA_MUJ",
      "label": "Nuca",
      "gender": "mujer",
      "pricePerSession": 50000
    },
    {
      "key": "CUELLO_MUJ",
      "label": "Cuello",
      "gender": "mujer",
      "pricePerSession": 50000
    },
    {
      "key": "ESCOTE_MUJ",
      "label": "Escote",
      "gender": "mujer",
      "pricePerSession": 52000
    },
    {
      "key": "PEZON_MUJ",
      "label": "Pezón",
      "gender": "mujer",
      "pricePerSession": 46000
    },
    {
      "key": "CADERA_MUJ",
      "label": "Cadera",
      "gender": "mujer",
      "pricePerSession": 64000
    },
    {
      "key": "PIES_MUJ",
      "label": "Pies",
      "gender": "mujer",
      "pricePerSession": 46000
    },
    {
      "key": "FRENTE_MUJ",
      "label": "Frente",
      "gender": "mujer",
      "pricePerSession": 46000
    },
    {
      "key": "ENTRECEJO_MUJ",
      "label": "Entrecejo",
      "gender": "mujer",
      "pricePerSession": 42000
    },
    {
      "key": "MAMAS_MUJ",
      "label": "Mamas",
      "gender": "mujer",
      "pricePerSession": 58000
    },
    {
      "key": "MEJILLAS_MUJ",
      "label": "Mejillas",
      "gender": "mujer",
      "pricePerSession": 46000
    },
    {
      "key": "CEJAS_ENT_MUJ",
      "label": "Cejas y entrecejo",
      "gender": "mujer",
      "pricePerSession": 68000
    },
    {
      "key": "HOMBROS_MUJ",
      "label": "Hombros",
      "gender": "mujer",
      "pricePerSession": 54000
    },
    {
      "key": "ROSTRO_COMP_HOM",
      "label": "Rostro completo",
      "gender": "hombre",
      "pricePerSession": 74000
    },
    {
      "key": "CUELLO_HOM",
      "label": "Cuello",
      "gender": "hombre",
      "pricePerSession": 54000
    },
    {
      "key": "BRAZOS_HOM",
      "label": "Brazos completos",
      "gender": "hombre",
      "pricePerSession": 74000
    },
    {
      "key": "ANTEBR_HOM",
      "label": "Antebrazos",
      "gender": "hombre",
      "pricePerSession": 60000
    },
    {
      "key": "TORAX_HOM",
      "label": "Tórax",
      "gender": "hombre",
      "pricePerSession": 100000
    },
    {
      "key": "PECHO_HOM",
      "label": "Pecho",
      "gender": "hombre",
      "pricePerSession": 82000
    },
    {
      "key": "ABDOMEN_HOM",
      "label": "Abdomen",
      "gender": "hombre",
      "pricePerSession": 78000
    },
    {
      "key": "ESP_COMP_HOM",
      "label": "Espalda completa",
      "gender": "hombre",
      "pricePerSession": 100000
    },
    {
      "key": "ESP_BAJA_HOM",
      "label": "Espalda baja",
      "gender": "hombre",
      "pricePerSession": 70000
    },
    {
      "key": "ESP_ALTA_HOM",
      "label": "Espalda alta",
      "gender": "hombre",
      "pricePerSession": 76000
    },
    {
      "key": "ESP_ALTA_HOMBROS_HOM",
      "label": "Espalda alta + hombros",
      "gender": "hombre",
      "pricePerSession": 138000
    },
    {
      "key": "BARBA_HOM",
      "label": "Barba",
      "gender": "hombre",
      "pricePerSession": 54000
    },
    {
      "key": "HOMBROS_HOM",
      "label": "Hombros",
      "gender": "hombre",
      "pricePerSession": 66000
    },
    {
      "key": "PIERNAS_HOM",
      "label": "Piernas completas",
      "gender": "hombre",
      "pricePerSession": 86000
    },
    {
      "key": "GLUTEOS_HOM",
      "label": "Glúteos",
      "gender": "hombre",
      "pricePerSession": 70000
    },
    {
      "key": "CAVADO_HOM",
      "label": "Cavado",
      "gender": "hombre",
      "pricePerSession": 68000
    },
    {
      "key": "TIRA_HOM",
      "label": "Tira",
      "gender": "hombre",
      "pricePerSession": 54000
    },
    {
      "key": "EMPEINE_HOM",
      "label": "Empeine",
      "gender": "hombre",
      "pricePerSession": 46000
    },
    {
      "key": "DEDOS_HOM",
      "label": "Dedos",
      "gender": "hombre",
      "pricePerSession": 46000
    },
    {
      "key": "MANOS_HOM",
      "label": "Manos",
      "gender": "hombre",
      "pricePerSession": 46000
    },
    {
      "key": "NUCA_HOM",
      "label": "Nuca",
      "gender": "hombre",
      "pricePerSession": 54000
    },
    {
      "key": "SUB_MENTON_HOM",
      "label": "Submentón",
      "gender": "hombre",
      "pricePerSession": 54000
    },
    {
      "key": "AXI_HOM",
      "label": "Axilas",
      "gender": "hombre",
      "pricePerSession": 54000
    },
    {
      "key": "FRENTE_HOM",
      "label": "Frente",
      "gender": "hombre",
      "pricePerSession": 46000
    },
    {
      "key": "OREJAS_HOM",
      "label": "Orejas",
      "gender": "hombre",
      "pricePerSession": 46000
    },
    {
      "key": "POMULOS_HOM",
      "label": "Pómulos",
      "gender": "hombre",
      "pricePerSession": 54000
    },
    {
      "key": "ESP_ALTA_NUCA_CUELLO_HOM",
      "label": "Espalda alta+nuca+cuello",
      "gender": "hombre",
      "pricePerSession": 174000
    },
    {
      "key": "MP_HOM",
      "label": "Media pierna",
      "gender": "hombre",
      "pricePerSession": 62000
    },
    {
      "key": "BIGOTE_HOM",
      "label": "Bigote",
      "gender": "hombre",
      "pricePerSession": 54000
    },
    {
      "key": "MPS_HOM",
      "label": "Media pierna superior",
      "gender": "hombre",
      "pricePerSession": 76000
    }
  ]
}
